spring.application.name=api-gateway
server.port=8080

# Microservices routing targets
services.team-url=http://localhost:8081
services.match-url=http://localhost:8082
services.standing-url=http://localhost:8083
