spring.application.name=match-service
server.port=8082

# Database Configuration (SQL Server Docker - Database per service)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ScoreCraft_Matches;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=SmartFill2024!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
